### ISSUE TITLE
About RealmEyeSharper

### ISSUE THREAD

**Issue by TimurBas** [ewang2002/RealmEyeSharper#8] opened 2022-01-15 10:53 UTC
Hi Ewang, I crossed over your RealmEyeSharper project as I am trying to make my own little project based on data from RealmEye. However, I get 403 Forbidden when trying to download data from the website. I can see that you do something with proxies and a lot of user agents but what is the whole idea? If you don't mind can you enlighten me on why you designed RealmEyeSharper with proxies and such?

Thanks.

**Comment by ewang2002** [comment] 2022-01-15 17:10
Hi TimurBas,
One of the things I tried to do was see if I could get multiple player's profiles at the same time without hitting RealmEye's rate limit. As you know, RealmEye has a pretty strict rate limit (it's strict to the point where, for example, if many people are trying to verify with the bot that has to use the API, the API can get rate limited). 

Now, I'm not sure if you're familiar with raiding Discord servers (like Public Lost Halls or Shatters), but a lot of these servers often have a bot that parses raids (using a /who) to see who's crashing raids. This, by itself, doesn't require using proxies to getaround a rate limit; however, I had the idea of implementing a parse command that also checked to see if there were people joining raids that were undergeared (which required me to make upwards of 80 requests, all of which needed to be done within 5 seconds or so). I have since stopped working on that aspect of the project.

Now, the API was designed so that, if you don't have a proxy key, it should default to the general way of getting data from RealmEye. The general way is just using a regular `HttpClient` to fetch the page's HTML and then scraping it, which shouldn't cause any problems. 

To answer your question regarding the 403 Forbidden error:
- If this was caused by you using my API: can you confirm check and see if the API is making use of proxies to make requests? Note that all requests for RealmEye pages are made [here](https://github.com/ewang2002/RealmEyeSharper/blob/master/RealmAspNet/RealmEye/RealmEyeCommon.cs), specifically in line 33. Additionally, in the console, the API should tell you if the proxy is being used (for example, it should print "Using Proxy").
- If you're using my code in your project, make sure you aren't including the proxy stuff in your code.

Thanks!

(And also, note that I transferred this issue to the appropriate repository.)

**Comment by TimurBas** [comment] 2022-01-15 18:33
Hi again, I now understand why you used proxies, thanks for the thorough explanation (and yes, I do know about those raid Discords 💯 )

I'm not using your project but  (solved the 403 by looking at what you did), so the error was on my behalf since I did not include a user agent in the header, apparently, dunno why it works actually. 
I'm also just scraping it by downloading the HTML for the corresponding pages.

Now I'm curious, how did u find out the limit that RealmEye has? I could imagine RealmEye limits requests from IPs (since you used proxies), is this the case?

Sincerely, Timur Bas.

**Comment by ewang2002** [comment] 2022-01-15 18:49
I found out that RealmEye had rate limits from other developers that tried to do the same thing. Plus, as I said, there was a period of time when my bot (using my API) had a lot of people trying to make API requests, which triggered rate limits and crashed my bot.

One thing you can always try is just send a bunch of requests and see how fast it takes for you to get rate limited. It's very unlikely you'll get banned for just spamming them once. Usually, when you get rate limited, the server will respond back with a header containing information about your rate limit.

**Comment by TimurBas** [comment] 2022-01-16 05:26
Alright, that makes sense, thanks for the information!

**Comment by ewang2002** [comment] 2022-01-16 08:24
Of course! I'm glad I could help. If you have any other questions, feel free to contact me again! :)

I'll be closing this now.

**Closed as completed by ewang2002** 2022-01-16 08:24 UTC
Labels: bug
